name: Pre run
description: "NPM Install and retrieve current release"
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: storage/package-lock.json
    # - name: NPM Install Storage
    #   shell: bash
    #   working-directory: storage
    #   run: npm i
    install_all:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - name: Install All
        run: |
           chmod +x ../../../../setup.sh
           ../../../../setup.sh
    # Since each job may only update a subset of files, we pull the
    # current release so that we update the release, we have all the files.
    - name: Retrieve Current Release
      shell: bash
      working-directory: storage
      run: npx windy-civi-storage github ./dist_legislation
