name: Pre run
description: "NPM Install and retrieve current release"
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: storage/package-lock.json
    - uses: actions/checkout@v2
    - name: Install All
      working-directory: ./
      shell: bash
      run: |
        chmod +x ./setup.sh
        ./setup.sh
