# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Domain Quality
on:
  pull_request:
  merge_group:

jobs:
  lint:
    name: 🔬 Domain Quailty Checks
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 NPM Install
        working-directory: domain
        run: npm i

      - name: 🔬 Quality
        working-directory: domain
        run: npm run quality

      - name: 🧪 Tests
        working-directory: domain
        run: npm run test
