name: Scraper Summaries

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 0:00 UTC (7pm Central)

  # Allow manual running from Github Actions tab
  workflow_dispatch:
    inputs:
      locale:
        type: string
        description: Run only on 1 locale
      skip_cache:
        type: boolean
        description: Skip Cache - Force update all summaries?

jobs:
  update_summaries:
    name: ✨ Generate Summaries
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: 🎟️ Checkout repository
        uses: actions/checkout@v3
      - name: ⬇️ Install All
        uses: ./.github/workflows/compose/install-all
        with:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Retrieve Current Release
        working-directory: scraper
        run: npm run copy-release

      - name: Run GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SKIP_CACHE: ${{inputs.skip_cache}}
          LOCALE: ${{inputs.locale}}
        working-directory: scraper
        run: npm run gpt

      - name: Run Wiki
        env:
          GOOGLE_SPREADSHEET_API_KEY: ${{ secrets.GOOGLE_SPREADSHEET_API_KEY }}
        working-directory: scraper
        run: npm run wiki

      - name: Publish
        uses: ./.github/workflows/compose/publish-data
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
